"""rename address

Revision ID: 007372792a7e
Revises: d1a8932c14fd
Create Date: 2024-06-26 18:34:44.323025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007372792a7e'
down_revision = 'd1a8932c14fd'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic 